version: '3'

services:
  db:
    image: postgres:9.6.4-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    entrypoint: /docker/app/docker-entrypoint.sh
    command: develop
    environment:
      DJANGO_SECRET_KEY: "DJANGO_SECRET_KEY"
      DJANGO_SETTINGS_MODULE: "config.settings.development"
      DJANGO_MANAGEPY_MIGRATE: "on"
      DATABASE_URL: "postgres://password:user@db:5432/db_name"
      DJANGO_ALLOWED_HOSTS: "localhost"
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
